# Generated by Django 5.2.7 on 2025-11-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbill',
            unique_together=set(),
        ),
    ]
