# Generated by Django 5.2.7 on 2025-11-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0003_alter_userbill_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distributor_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
