# Generated by Django 5.2.7 on 2025-10-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0004_remove_order_order_id_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
