# Generated by Django 5.2.7 on 2025-11-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
