# Generated by Django 5.1.2 on 2025-10-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0006_alter_order_status_userbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbill',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
