# Generated by Django 5.2.7 on 2025-11-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0007_distributororder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbill',
            name='type',
            field=models.CharField(choices=[('customer_bill', 'Customer Bill'), ('distributor_bill', 'Distributor Bill')], default='customer_bill', max_length=50),
        ),
    ]
