# Generated by Django 5.2.7 on 2025-11-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0008_userbill_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBill',
        ),
    ]
