# Generated by Django 5.2.7 on 2025-12-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0011_alter_cacheorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache_products', to='dairy.product'),
        ),
    ]
