# Generated by Django 5.2.7 on 2026-01-09 16:01

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0012_alter_cacheorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='products/'),
        ),
    ]
