# Generated by Django 5.2.7 on 2026-01-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0013_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributororder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='distributor_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
