# Generated by Django 5.2.7 on 2025-10-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
