# Generated by Django 5.2.7 on 2025-10-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('distributor', 'Distributor'), ('delivery_staff', 'Delivery Staff'), ('customer', 'Customer')], default='customer', max_length=20, null=True),
        ),
    ]
