# Generated by Django 5.2.7 on 2025-11-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_address_user_city_user_country_user_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
