# Generated by Django 5.2.7 on 2025-10-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('distributor', 'Distributor'), ('delivery_staff', 'Delivery Staff'), ('customer', 'Customer')], max_length=20, null=True),
        ),
    ]
