# Generated by Django 5.2.7 on 2025-10-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
