# Generated by Django 5.2.7 on 2025-11-30 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account_no', models.PositiveIntegerField()),
                ('bank_name', models.CharField(max_length=255)),
                ('holder_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('qr', models.ImageField(upload_to='qr_code/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='QrCode',
        ),
    ]
