# Generated by Django 5.2.7 on 2025-10-05 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_reset_password_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverificationtoken',
            old_name='email_verification_token_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='role_accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
