# Generated by Django 5.2.7 on 2025-11-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_bankaccount_delete_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='gst_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
