# Generated by Django 5.2.7 on 2025-11-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_bankaccount_gst_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_no',
            field=models.CharField(max_length=20),
        ),
    ]
