# Generated by Django 5.2.7 on 2025-10-06 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_user_address_remove_user_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_accepted_by',
        ),
        migrations.AddField(
            model_name='user',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
