# Generated by Django 5.2.7 on 2025-10-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
