# Generated by Django 5.2.7 on 2025-10-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_role_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allow_notification',
        ),
    ]
