# Generated by Django 5.2.7 on 2025-12-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_populate_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code/'),
        ),
    ]
