# Generated by Django 5.2.7 on 2025-12-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_bankaccount_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pause',
            field=models.BooleanField(default=False),
        ),
    ]
