# Generated by Django 5.2.7 on 2025-10-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_role_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
