# Generated by Django 5.2.7 on 2025-12-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_is_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_pause',
            field=models.BooleanField(default=True),
        ),
    ]
