# Generated by Django 5.2.7 on 2026-01-09 16:42

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_user_is_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='qr',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='qr_code/'),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='bills/'),
        ),
    ]
