# Generated by Django 5.2.7 on 2026-01-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_bankaccount_qr_alter_userbill_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Customer balance: payments - delivered orders', max_digits=10),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
